.TH BUBBLES 6 ICL
.SH NAME
bubbles \- animated bubble display
.SH SYNOPSIS
.B bubbles
.SH DESCRIPTION
.IX  "bubbles command"  ""  "\fLbubbles\fP \(em display bubbles"
.LP
Display a tank full of bubbles on a crt. Restful on the eyes if not on
async. terminal comms. 
.SH FILES
.PD 0 
.TP 20
.B /etc/termcap
.PD
