.TH BUBBLES 6 ICL
.SH NAME
bubbles \- animated bubble display
.SH SYNOPSIS
.B bubbles
[OPTION]
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-delay\fR \fIDELAY\fR
update interval in millisecond. (Default: 500)
.SH DESCRIPTION
.IX  "bubbles command"  ""  "\fLbubbles\fP \(em display bubbles"
.LP
Display a tank full of bubbles on a crt. Restful on the eyes if not on
async. terminal comms. 
.SH FILES
.PD 0 
.TP 20
.B /etc/termcap
.PD
.SH AUTHORS
.UR http://www.zois.co.uk/people/martin_sullivan/
Martin Sullivan
.UE
is the original author of \fBbubbles.c\fP.
This version is maintained by
.MT livibetter@\:gmail.com
Yu-Jie Lin
.ME
since July, 2014 on
.UR https://bitbucket.org/livibetter/clock
Bitbucket
.UE .
